-- 01_schema.sql (base + gasto_fijo_mes)
create extension if not exists pgcrypto;
create extension if not exists "uuid-ossp";
do $$ begin if not exists (select 1 from pg_type where typname='grupo_vaso') then create type grupo_vaso as enum ('NONE','VASO10','VASO15'); end if; end $$;
create table if not exists punto (id uuid primary key default gen_random_uuid(), nombre text not null unique, activo boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists medio_pago (id uuid primary key default gen_random_uuid(), nombre text unique not null, activo boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists cajero (id uuid primary key default gen_random_uuid(), nombre text not null, activo boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists sku (id uuid primary key default gen_random_uuid(), codigo text unique not null, nombre text not null, categoria text, punto_id uuid references punto(id), grupo_vaso grupo_vaso default 'NONE', precio_vigente numeric not null check (precio_vigente>=0), activo boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists venta_tx (id uuid primary key default gen_random_uuid(), fecha date not null, hora time not null, punto_id uuid not null references punto(id), cajero_id uuid references cajero(id), sku_id uuid not null references sku(id), cantidad int not null check(cantidad>0), precio_unitario numeric not null check(precio_unitario>=0), medio_pago_id uuid not null references medio_pago(id), total numeric generated always as (cantidad*precio_unitario) stored, nota text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists venta_total_dia (id uuid primary key default gen_random_uuid(), fecha date not null, punto_id uuid not null references punto(id), total_venta_dia numeric not null check(total_venta_dia>=0), unique(fecha,punto_id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists gasto (id uuid primary key default gen_random_uuid(), fecha date not null, punto_id uuid not null references punto(id), medio_pago_id uuid references medio_pago(id), categoria text not null check (categoria in ('Insumos','Licorera','Arriendo','Servicios','Varios','Prestamos/Anticipos')), concepto text, monto numeric not null check(monto>=0), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists nomina (id uuid primary key default gen_random_uuid(), fecha date not null, persona text not null, cargo text, punto_id uuid references punto(id), medio_pago_id uuid references medio_pago(id), monto numeric not null check(monto>=0), nota text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists descuento (id uuid primary key default gen_random_uuid(), fecha date not null, punto_id uuid references punto(id), tipo text not null check (tipo in ('Socio','Cortesia','Promocion')), persona text, concepto text, monto numeric not null check(monto>=0), sku_id uuid references sku(id), cantidad int, nota text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists vasos_dia (id uuid primary key default gen_random_uuid(), fecha date not null, inicial_10 int default 0, entradas_10 int default 0, final_10 int default 0, inicial_15 int default 0, entradas_15 int default 0, final_15 int default 0, unique(fecha), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists cierre_punto (id uuid primary key default gen_random_uuid(), fecha date not null, punto_id uuid not null references punto(id), efectivo_real numeric not null check(efectivo_real>=0), obs text, unique(fecha,punto_id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists socio (id uuid primary key default gen_random_uuid(), nombre text not null, porcentaje_global numeric not null check(porcentaje_global>=0 and porcentaje_global<=1));
create table if not exists mov_socio (id uuid primary key default gen_random_uuid(), fecha date not null, socio_id uuid references socio(id), punto_id uuid references punto(id), tipo text check (tipo in ('Cargo','Abono')), concepto text, monto numeric not null check(monto>=0));
create table if not exists gasto_fijo_mes (id uuid primary key default gen_random_uuid(), mes date not null, concepto text not null, monto numeric not null check(monto>=0), unique (mes, concepto));
